# Generated by Django 5.1.3 on 2026-04-29 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaassets',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='mediaassets',
            name='description',
            field=models.TextField(blank=True, default='uploaded and maintained by MEDIAHUB'),
        ),
        migrations.AlterField(
            model_name='mediaassets',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediaassets',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
